---
- name: Use the file module to remove a file
  hosts: all
  remote_user: devops
  
  tasks:
    - name: Remove a file from managed hosts
      ansible.builtin.file:
        path: /homedevops/users.txt
        state: absent
