---
- name: Resolve host patterns
  hosts: europe
    #db,&london
    #'172.*,*lab*'
    #
    #'172.25.*'
    #lb1.lab.example.com,s1.lab.example.com,db1.example.com
    #'*.example.com'
    #'*.example.com , !*.lab.example.com'
    #all
    #172.25.252.44 
    #db1.example.com
  gather_facts: no
  tasks:
  - name: Display managed hosts matching the host pattern
    ansible.builtin.debug:
      msg: "{{ inventory_hostname }}"

