
---
- name: Ensure backups are taken
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    backup_target: /etc
    backup_store: /var/tmp/backup
    backup_format: xz
    backup_file: /var/tmp{{ backup_target | basename}}_{{
      ansible_facts['date_time']['iso8601'] }}.tar.{{ backup_format }}
  tasks:
    - name: Ensure {{ backup_store }} exists
      become: false
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ backup_store }}/{{ inventory_hostname }}"
        owner: student
        state: directory
    - name: Ensure backup of {{ backup_target }} exists
      community.general.archive:
        path: "{{ backup_target }}"
        dest: "{{ backup_file }}"
        format: "{{ backup_format }}"
    - name: Ensure backup is stored on controller
      ansible.builtin.fetch:
        src: "{{ backup_file }}"
    - name: Ensure backup is stored on controller
      ansible.builtin.fetch:
        src: "{{ backup_file }}"
        dest: "{{ backup_store }}/{{ inventory_hostname }}/"
        flat: true
